version: "3.8"

services:
  mysql:
    image: mysql:8.0
    restart: always
    ports:
      - "6000:3306"
    environment:
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
